version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: manager
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: revolutdb
    volumes:
      - "./www-data:/var/www/html"
      - ./php.ini-custom:/usr/local/etc/php/conf.d/php.ini

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: revolutdb
      MYSQL_USER: manager
      MYSQL_PASSWORD: secret
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: